### ISSUE TITLE
Card only shows 6 rows

### ISSUE THREAD

**Issue by glitchphan** [cryptofuture/PassCard#4]
The new version from F-Droid works for me now on  6.0.1 ROM, but the card only shows 6 of the 8 rows. There's no point in the border of the card taking up space, it seems.

**Comment by cryptofuture** [comment]
Nice idea with border, I'll give it a look.

**Comment by cryptofuture** [comment]
I remade app to 8 rows. (9-1) I tried place bar in bottom but its not handy that way.

**Comment by glitchphan** [comment]
It looks great now with latest update on F-Droid (1.4). You get all rows and you can zoom in so everything fits nicely taking up the entire screen. Thanks!
