### ISSUE TITLE
Which dependencies and versions are required?

### ISSUE THREAD

**Issue by krt16s** [cryptofuture/PassCard#5]
I failed to build the recent version of this app, I tried to bump supportlib versions but still failed. Could you provide a list of dependencies and corresponding version? Maybe it owuld even be possible to upgrade to the more recent gradle build system used by AndroidStudio?

**Comment by cryptofuture** [comment]
Hi, you tried to disable proguard? Will try to build now from version github, through it should be the same, maybe I added some files to gitignore again.

**Comment by cryptofuture** [comment]
Well I tried and imported and build it without problem. Through I needed to specify that I need to build MainActivity. But I think this is IDEA problem, that never knew what to build first, with gradle I need  activity selection too. I have nothing in external libraries beside 4.4.2 sdk after import.

**Comment by cryptofuture** [comment]
Anyway only file with js and html file in assets folder changed since 1.1. Have no idea, what prevents f-droid server from making build.

**Comment by krt16s** [comment]
Building as usual errors with

````
    [javac] Compiling 4 source files to /home/krt/src/fdroiddata/build/com.passcard/bin/classes
    [javac] /home/krt/src/fdroiddata/build/com.passcard/src/com/passcard/MainActivity.java:20: error: cannot find symbol
    [javac]         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
    [javac]                                                         ^
    [javac]   symbol:   variable LOLLIPOP
    [javac]   location: class VERSION_CODES
    [javac] /home/krt/src/fdroiddata/build/com.passcard/src/com/passcard/MainActivity.java:21: error: cannot find symbol
    [javac]             WebViewPassCard.enableSlowWholeDocumentDraw();
    [javac]                            ^
    [javac]   symbol:   method enableSlowWholeDocumentDraw()
    [javac]   location: variable WebViewPassCard of type WebView
    [javac] 2 errors
````

So  `Build.VERSION_CODES.LOLLIPOP` looks like you updated to 5.x SDK or something.

**Comment by cryptofuture** [comment]
I changed lines to SDK version numbers, instead names. Give it a try please. In bad case, I will just remove this line.

**Comment by krt16s** [comment]
That doesn't solve it, however, I had a look at it, and the cause is this: You try to access methods introduced in higher API levels, 19 and 21. However, you Manifest file at https://github.com/cryptofuture/PassCard/blob/master/AndroidManifest.xml still says its targeting android-16. You should bump the target version and run `android update project -t android-21 -p ./ --subprojects` to adapt the build.

**Comment by cryptofuture** [comment]
I removed target version. I checked previous version, and previous version was without target version in manifest. Hope this will fix building.

**Comment by cryptofuture** [comment]
Closing issue. Build available in f-droid.

**Comment by krt16s** [comment]
Yep, build works indeed. Thanks.
